"""Text conversion page matching the battery extraction workspace."""
import tkinter as tk
from tkinter import ttk
from text_batch import MERGE_MODES
from ui_common import card, inner, file_table, wrap_label, icon, SettingsPanel, separator, summary_bar, responsive_drop


def build_text_view(self):
    self.columnconfigure(0,weight=1); self.rowconfigure(0,weight=1)
    files=card(self); files.grid(row=0,column=0,sticky='nsew',padx=(0,12))
    files.columnconfigure(0,weight=1); files.rowconfigure(3,weight=1)
    ttk.Label(files,text='TXT 转 Excel',style='Title.TLabel').grid(row=0,column=0,sticky='w',pady=(0,20))
    drop=ttk.Frame(files,style='Soft.TFrame',padding=(18,18)); drop.grid(row=1,column=0,sticky='ew',pady=(0,22))
    self.drop_zone=drop; drop.columnconfigure(1,weight=1)
    ttk.Label(drop,image=icon(self,'file',size=36),style='Soft.TLabel').grid(row=0,column=0,rowspan=2,padx=(0,16))
    ttk.Label(drop,text='拖入文本或文件夹',style='SoftTitle.TLabel').grid(row=0,column=1,sticky='w')
    subtitle=ttk.Label(drop,text='支持 TXT、CSV、TSV，自动识别 EIS / CV',style='SoftHint.TLabel',wraplength=330)
    subtitle.grid(row=1,column=1,sticky='w',pady=(6,0))
    buttons=ttk.Frame(drop,style='Soft.TFrame'); buttons.grid(row=0,column=2,rowspan=2,padx=(12,0))
    self.folder_button=ttk.Button(buttons,text='选择文件夹',image=icon(self,'folder',size=19),compound='left',command=lambda: self.choose(self.input))
    self.folder_button.pack(side='left',padx=(0,8)); self.controls.append(self.folder_button)
    self.add_button=ttk.Button(buttons,text='添加文件',image=icon(self,'add','#FFFFFF',19),compound='left',style='Primary.TButton',command=self.choose_files)
    self.add_button.pack(side='left'); self.controls.append(self.add_button)
    responsive_drop(drop,buttons,subtitle)
    toolbar=inner(files); toolbar.grid(row=2,column=0,sticky='ew',pady=(0,10))
    ttk.Label(toolbar,text='文件列表',style='Section.TLabel').pack(side='left')
    self.count_text=tk.StringVar(value='0 个文件')
    ttk.Label(toolbar,textvariable=self.count_text,style='CardHint.TLabel').pack(side='left',padx=12)
    self.more_button=ttk.Button(toolbar,text='更多操作 ▾',command=self.show_actions)
    self.more_button.pack(side='right'); self.controls.append(self.more_button)
    self.actions_menu=tk.Menu(self.more_button,tearoff=False,font=('Microsoft YaHei UI',11))
    self.actions_menu.add_command(label='清空列表',command=self.clear_files)
    self.remove_button=ttk.Button(toolbar,text='移除选中',image=icon(self,'trash','#70839E',18),compound='left',command=self.remove_files,state='disabled')
    self.remove_button.pack(side='right',padx=(0,10)); self.controls.append(self.remove_button)
    table,self.tree=file_table(files,('file','kind','status','rows'),('文件名称','类型','处理状态','数据行数'),(400,70,175,100),multiple=True)
    table.grid(row=3,column=0,sticky='nsew')
    self.empty_hint=ttk.Label(table,text='还没有文件\n从上方添加，或直接拖入',style='CardHint.TLabel',justify='center')
    self.empty_hint.place(relx=.5,rely=.5,anchor='center')
    self.tree.bind('<<TreeviewSelect>>',self.show_selection); self.tree.bind('<Delete>',lambda _: self.remove_files())
    self.progress=ttk.Progressbar(files); self.progress.grid(row=4,column=0,sticky='ew',pady=(10,0))
    self.detail=tk.StringVar(value=''); wrap_label(files,self.detail).grid(row=5,column=0,sticky='ew',pady=(8,0))
    summary_bar(files,self,6)
    options=SettingsPanel(self,'转换设置'); options.grid(row=0,column=1,sticky='nsew'); self.settings_panel=options
    body=options.content
    ttk.Label(body,text='处理类型',style='Section.TLabel').grid(row=0,column=0,sticky='w',pady=(0,10))
    types=inner(body); types.grid(row=1,column=0,sticky='ew'); self.kinds={}
    for kind,label in [('EIS','EIS 阻抗'),('CV','CV 循环伏安'),('通用','普通表格')]:
        variable=tk.BooleanVar(value=True); self.kinds[kind]=variable
        box=ttk.Checkbutton(types,text=label,variable=variable); box.pack(anchor='w',pady=3); self.controls.append(box)
    ttk.Label(body,text='合并方式',style='Section.TLabel').grid(row=2,column=0,sticky='w',pady=(18,12))
    self.merge=tk.StringVar(value=MERGE_MODES[1])
    self.merge_box=ttk.Combobox(body,textvariable=self.merge,values=MERGE_MODES,state='readonly',width=23)
    self.merge_box.grid(row=3,column=0,sticky='ew')
    separator(body,4)
    ttk.Label(body,text='保存位置',style='Section.TLabel').grid(row=5,column=0,sticky='w',pady=(0,12))
    entry=ttk.Entry(body,textvariable=self.output,width=26); entry.grid(row=6,column=0,sticky='ew'); self.controls.append(entry)
    entry.bind('<FocusOut>',lambda _: self.remember_paths()); entry.bind('<Return>',lambda _: self.remember_paths())
    button=ttk.Button(body,text='选择位置',command=lambda: self.choose(self.output))
    button.grid(row=7,column=0,sticky='e',pady=(10,0)); self.controls.append(button)
    separator(body,8)
    self.settings_button=ttk.Button(body,text='更多设置 ▾',style='Quiet.TButton',command=self.toggle_settings)
    self.settings_button.grid(row=9,column=0,sticky='w'); self.controls.append(self.settings_button)
    self.advanced_window = tk.Toplevel(self)
    self.advanced_window.withdraw()
    self.advanced_window.title('文本转换 · 更多设置')
    self.advanced_window.transient(self.winfo_toplevel())
    self.advanced_window.geometry('880x470')
    self.advanced_window.minsize(800, 440)
    self.advanced_window.protocol('WM_DELETE_WINDOW', self.advanced_window.withdraw)
    self.advanced = inner(self.advanced_window, padding=18); self.advanced.pack(fill='both', expand=True)
    general=inner(self.advanced); general.pack(fill='x',pady=(0,14)); general.columnconfigure(1,weight=1)
    ttk.Label(general,text='输入文件夹',style='CardHint.TLabel').grid(row=0,column=0,padx=(0,12))
    self.input_entry=ttk.Entry(general,textvariable=self.input); self.input_entry.grid(row=0,column=1,sticky='ew'); self.controls.append(self.input_entry)
    self.input_entry.bind('<Return>',lambda _: self.scan_folder()); self.input_entry.bind('<FocusOut>',lambda _: self.scan_folder())
    recursive_box=ttk.Checkbutton(general,text='包含子文件夹',variable=self.recursive,command=self.scan_folder)
    recursive_box.grid(row=1,column=0,columnspan=2,sticky='w',pady=(8,0)); self.controls.append(recursive_box)
    settings = ttk.Notebook(self.advanced, style='Settings.TNotebook'); settings.pack(fill='x')
    eis, cv, generic = [ttk.Frame(settings, padding=12, style="Inner.TFrame") for _ in range(3)]
    for panel, name in zip((eis, cv, generic), ('EIS 阻抗', 'CV 分圈与找峰', '普通表格')): settings.add(panel, text=name)
    self.eis_simple, self.cv_split = tk.BooleanVar(value=False), tk.BooleanVar(value=True)
    box = ttk.Checkbutton(eis, text='仅导出 Z′、−Z″', variable=self.eis_simple)
    box.pack(anchor='w'); self.controls.append(box)
    cv.columnconfigure(0, weight=1)
    box = ttk.Checkbutton(cv, text='按圈并排', variable=self.cv_split)
    box.grid(row=0, column=0, sticky='w'); self.controls.append(box)
    peak = inner(cv); peak.grid(row=1, column=0, sticky='ew', pady=(6, 4))
    self.low, self.high, self.extreme = tk.StringVar(), tk.StringVar(), tk.StringVar(value='最小电流')
    for label, variable in [('下限 V', self.low), ('上限 V', self.high)]:
        ttk.Label(peak, text=label, style='CardHint.TLabel').pack(side='left', padx=(0, 5))
        entry = ttk.Entry(peak, textvariable=variable, width=7)
        entry.pack(side='left', padx=(0, 12)); self.controls.append(entry)
    self.extreme_box = ttk.Combobox(peak, textvariable=self.extreme, values=('最小电流', '最大电流'), state='readonly', width=8)
    self.extreme_box.pack(side='left', padx=(0, 8))
    for label, command in [('添加区间', self.add_range), ('移除选中', self.remove_range)]:
        button = ttk.Button(peak, text=label, command=command)
        button.pack(side='left', padx=4); self.controls.append(button)
    self.range_list = tk.Listbox(cv, height=2, font=('Microsoft YaHei UI', 11), exportselection=False,
                                relief='flat', borderwidth=0, highlightthickness=0, background='#F3F5F7',
                                selectbackground='#E8F0FD', selectforeground='#263445')
    self.range_list.grid(row=2, column=0, sticky='ew')
    self.delimiter, self.header = tk.StringVar(value='自动'), tk.StringVar(value='自动')
    self.generic_boxes = []
    for row, (label, variable, values) in enumerate([('分隔符', self.delimiter, ('自动', '逗号', '制表符', '分号', '空白')), ('表头', self.header, ('自动', '首行为表头', '无表头'))]):
        ttk.Label(generic, text=label, style='CardHint.TLabel').grid(row=row, column=0, sticky='w', padx=(0, 12), pady=5)
        box = ttk.Combobox(generic, textvariable=variable, values=values, state='readonly', width=20)
        box.grid(row=row, column=1, sticky='w'); self.generic_boxes.append(box)
    ttk.Button(self.advanced, text='完成设置', command=self.advanced_window.withdraw, style='Primary.TButton').pack(side='bottom', anchor='e', pady=(12, 0))
    self.start_button=ttk.Button(options.actions,text='▶  开始转换',command=self.start,style='Large.TButton')
    self.start_button.pack(fill='x')
    self.stop_button=ttk.Button(options.actions,text='停止后续文件',command=self.stop,state='disabled')
    self.open_button=ttk.Button(options.actions,text='打开结果文件夹',image=icon(self,'open',size=20),compound='left',command=self.open_results,state='disabled')
    self.open_button.pack(fill='x',pady=(10,0))
